target_column: "Satisfaction"

split:
  test_size: 0.30
  val_ratio: 0.50
  random_state: 42
model:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  random_state: 42

automl:
  presets: "medium_quality"
  time_limit: 120
  eval_metric: "root_mean_squared_error"